Update zsh prompt for semantic zones

diff --git a/zsh/prompt b/zsh/prompt
--- a/zsh/prompt
+++ b/zsh/prompt
@@ -65,6 +65,7 @@ function update_rprompt() {
   # Strip color codes from prompt to get real size
   unsetopt RE_MATCH_PCRE
   regexp-replace rpromptsize "\[([0-9]{1,2}(;[0-9]{1,2}(;[0-9]{1,3})?)?)?[m|K]"
+  regexp-replace rpromptsize "]133;[PB](;k=[iscr])?"
 
   # Go back to the start of current prompt and reprint it
   echo -ne "\e[A\e[$(( $COLUMNS - $#rpromptsize + 1 ))G$rprompt\e[B\e[G"
@@ -103,10 +104,20 @@ function {
   local name="%(!.$bold_magenta.$blue)%n$bold_cyan"
   local last_exit="${bold_red}%(?..E:%? )"
 
-  PROMPT="$ul$open$red%m$reset:%\$_pr_pwdlen<…<\$_pr_pwd%<<$close\$_pr_fillwidth\${_pr_extras:+$open$reset\${(j: :)_pr_extras}$close$ur"$'\n'"$ll$open$last_exit\${(j: :)_pr_short_extras}\${_pr_short_extras:+ }\$__prompt_mode$close%(!.$red.$black)⎬$reset "
+  local wezterm_start="$(echo -n "%{\e]133;P;k=i\a%}")" # "%{\033]133;P;k=i\007%}" # P k=i
+  local wezterm_continue="$(echo -n "%{\e]133;P;k=c\a%}")" # "%{\033]133;P;k=c\007%}" # P k=c
+  local wezterm_end="$(echo -n "%{\e]133;B\a%}")" # "%{\033]133;B\007%}" # B
+
+  # While we can mark the rprompt, the format of our prompt makes most jump sense to not mark it.
+  # local wezterm_rprompt_start="$(echo -n "%{\e]133;P;k=r\a%}")" # "%{\033]133;P;k=r\007%}" # P k=r
+  # local wezterm_rprompt_end="$wezterm_end"
+  local wezterm_rprompt_start=""
+  local wezterm_rprompt_end=""
+
+  PROMPT="$wezterm_start$ul$open$red%m$reset:%\$_pr_pwdlen<…<\$_pr_pwd%<<$close\$_pr_fillwidth\${_pr_extras:+$open$reset\${(j: :)_pr_extras}$close$ur"$'\n'"$ll$open$last_exit\${(j: :)_pr_short_extras}\${_pr_short_extras:+ }$wezterm_end$wezterm_continue\$__prompt_mode$close%(!.$red.$black)⎬$reset $wezterm_end"
   # PROMPT="$ll$open$last_exit\${(j: :)_pr_short_extras}\${_pr_short_extras:+ }\$__prompt_mode$close%(!.$red.$black)⎬$reset "
-  RPROMPT=" $open$reset%D{%H:%M} ${bold_cyan}on$reset %D{%a %b %d}$close\${_pr_extras:+${(qqq)lr}}$reset"
-  PS2="$open$bold_cyan%_$close$reset "
+  RPROMPT="$wezterm_rprompt_start $open$reset%D{%H:%M} ${bold_cyan}on$reset %D{%a %b %d}$close\${_pr_extras:+${(qqq)lr}}$reset$wezterm_rprompt_end"
+  PS2="$(echo -n "%{\e]133;P;k=s\a%}")$open$bold_cyan%_$close$reset $wezterm_end"
   PROMPT_EOL_MARK="%b%F{77}§$reset"
 }
 
@@ -363,6 +374,7 @@ function _prompt_precmd {
     promptsize=${${(S%%)PROMPT}//\~/b}
     promptsize=${${(ps:\n:)promptsize}[1]}
     regexp-replace promptsize "\[([0-9]{1,2}(;[0-9]{1,2}(;[0-9]{1,3})?)?)?[m|K]"
+    regexp-replace promptsize "]133;[PB](;k=[iscr])?"
     promptsize=$(( $#promptsize - $pwdsize + 1 ))
   }
   calc_promptsize
@@ -385,5 +397,35 @@ function _prompt_precmd {
   fi
 }
 precmd_functions+=_prompt_precmd
+
+function __wezterm_user_var() {
+  echo -en "\e]1337;SetUserVar=$1=$(echo -n "$2" | base64)\a"
+}
+
+function _wezterm_chpwd() {
+  # Inform wezterm of the current directory
+  echo -en "\e]7;file://$(hostname)${PWD}\e\\"
+}
+chpwd_functions+=_wezterm_chpwd
+
+function _wezterm_precmd() {
+  # Report the exit code of the last command
+  echo -en "\e]133;D;$?;aid=$$\a"
+  # Report the current working directory
+  __wezterm_user_var "WEZTERM_IN_TMUX" "$([ -n "${TMUX}" ] && echo -n 1 || echo -n 0)"
+  __wezterm_user_var "WEZTERM_PROG" ""
+  __wezterm_user_var "WEZTERM_USER" "$(id -un)"
+  __wezterm_user_var "WEZTERM_HOST" "$(hostname)"
+  # Start prompt
+  echo -en "\e]133;A;cl=m;aid=$$\a"
+}
+precmd_functions+=_wezterm_precmd
+
+function _wezterm_preexec() {
+  __wezterm_user_var "WEZTERM_PROG" "$1"
+  # Tell wezterm the command output starts here
+  echo -en "\e]133;C;\a"
+}
+preexec_functions+=_wezterm_preexec
 
 # vim: ft=zsh :
